### ISSUE TITLE
Betűtévesztések

### ISSUE THREAD

**Issue by zgroska** [tamas-ferenci/AdatvizualizacioBevezetes#1]
A konkrét esettanulmányunk a Nemzeti Rokragiszter (NRR) adatainak vizualizálása lesz.

Helyesen:

A konkrét esettanulmányunk a Nemzeti **Rákregiszter** (NRR) adatainak vizualizálása lesz.

**Comment by ferenci-tamas** [comment]
Itt valami nem stimmel. Megnéztem a forrásban is, a végeredményben is, én mindenhol 'á'-t látok:

![kép](https://user-images.githubusercontent.com/25476790/152236522-46fb0efa-1fad-45d4-a795-ebe714e891ad.png)

Szerintem nálad lesz valami baj, én sem tudom mi, de minden bizonnyal a karakterkódolással!
